// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCc58rKJdesQPTM7hEFFWMHqxf-04TOZMs',
    appId: '1:584601137066:web:55de52c493d1ba448a05d3',
    messagingSenderId: '584601137066',
    projectId: 'notepad-c2d3c',
    authDomain: 'notepad-c2d3c.firebaseapp.com',
    storageBucket: 'notepad-c2d3c.appspot.com',
    measurementId: 'G-D2FLQ2VZ44',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB934Vfs6VgQiw5j_0XKG93BbaesxaeHLE',
    appId: '1:584601137066:android:c13d59e3409ae79b8a05d3',
    messagingSenderId: '584601137066',
    projectId: 'notepad-c2d3c',
    storageBucket: 'notepad-c2d3c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXeaIZKbpz_S4geEF6O27IvycycSMgtSE',
    appId: '1:584601137066:ios:42439dbbeb3284fe8a05d3',
    messagingSenderId: '584601137066',
    projectId: 'notepad-c2d3c',
    storageBucket: 'notepad-c2d3c.appspot.com',
    iosClientId: '584601137066-kovhcl5rnrrn4j4cppooor1knllk5kqk.apps.googleusercontent.com',
    iosBundleId: 'com.example.notepad',
  );
}
